apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-auth-sa-role"
        vault.hashicorp.com/agent-inject-secret-config: "cfe/data/project/dev/web?version=9"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "cfe/data/project/dev/web" -}}
          API_USER="{{ .Data.data.username }}"
          {{- end -}}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: web
          image: codingforentrepreneurs/vault-py:latest
          env: 
              # - name: API_USER
              #   value: "Manifest test"
              - name: ENV_VERSION
                value: "1"
              - name: ENV_PATH
                value: /vault/secrets/config
              - name: PORT
                value: "8080"
          ports:
            - containerPort: 8080